import AppKit
import ImageIO

struct ClipItem: Identifiable, Equatable {
    enum Content: Equatable {
        case text(String)
        case image(thumbnail: NSImage, png: Data, size: CGSize)
    }

    let id = UUID()
    let content: Content
    let date: Date
    let sourceApp: String?

    var preview: String {
        switch content {
        case .text(let s):
            return s.trimmingCharacters(in: .whitespacesAndNewlines)
                .replacingOccurrences(of: "\n", with: " ⏎ ")
        case .image(_, let png, let size):
            let kb = png.count / 1024
            return "Görsel · \(Int(size.width))×\(Int(size.height)) · " + (kb >= 1024 ? "\(kb / 1024) MB" : "\(kb) KB")
        }
    }
}

@MainActor
final class ClipboardMonitor: ObservableObject {
    @Published private(set) var items: [ClipItem] = []

    var isEnabled = true
    let limit = 20
    let imageLimit = 6
    private let encoder = DispatchQueue(label: "dynamicisland.clipboard", qos: .utility)

    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?

    private static let skipTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    private static let passwordApps: Set<String> = [
        "com.apple.Passwords", "com.apple.keychainaccess", "com.1password.1password", "com.agilebits.onepassword7",
        "com.bitwarden.desktop", "com.lastpass.LastPass", "in.sinew.Enpass-Desktop", "com.dashlane.Dashlane",
        "org.keepassxc.keepassxc", "com.keepersecurity.passwordmanager", "me.proton.pass.electron",
    ]

    func start() {
        DistributedNotificationCenter.default().addObserver(
            forName: .init("com.apple.screenIsLocked"), object: nil, queue: .main
        ) { [weak self] _ in
            MainActor.assumeIsolated { self?.clear() }
        }
        timer = Timer.repeating(every: 1, tolerance: 0.3) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        guard isEnabled else { return }

        let types = pb.types ?? []
        if types.contains(where: Self.skipTypes.contains) { return }

        let front = NSWorkspace.shared.frontmostApplication
        if let id = front?.bundleIdentifier, Self.passwordApps.contains(id) { return }
        let source = front?.localizedName
        let item: ClipItem
        if let s = pb.string(forType: .string), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            items.removeAll { if case .text(let t) = $0.content { return t == s }; return false }
            item = ClipItem(content: .text(s), date: Date(), sourceApp: source)
        } else if types.contains(.tiff) || types.contains(.png),
                  let data = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            let isPNG = types.contains(.png)
            encoder.async { [weak self] in
                guard let content = Self.makeImageContent(data, isPNG: isPNG) else { return }
                DispatchQueue.main.async {
                    MainActor.assumeIsolated {
                        self?.insert(ClipItem(content: content, date: Date(), sourceApp: source))
                    }
                }
            }
            return
        } else {
            return
        }
        insert(item)
    }

    private func insert(_ item: ClipItem) {
        items.insert(item, at: 0)
        var images = 0
        items.removeAll { i in
            guard case .image = i.content else { return false }
            images += 1
            return images > imageLimit
        }
        if items.count > limit { items.removeLast(items.count - limit) }
    }

    private nonisolated static func makeImageContent(_ data: Data, isPNG: Bool) -> ClipItem.Content? {
        guard let src = CGImageSourceCreateWithData(data as CFData, nil),
              let props = CGImageSourceCopyPropertiesAtIndex(src, 0, nil) as? [CFString: Any] else { return nil }
        let size = CGSize(width: props[kCGImagePropertyPixelWidth] as? Int ?? 0,
                          height: props[kCGImagePropertyPixelHeight] as? Int ?? 0)
        let opts: [CFString: Any] = [kCGImageSourceCreateThumbnailFromImageAlways: true,
                                     kCGImageSourceThumbnailMaxPixelSize: 96,
                                     kCGImageSourceCreateThumbnailWithTransform: true]
        guard let thumbCG = CGImageSourceCreateThumbnailAtIndex(src, 0, opts as CFDictionary) else { return nil }
        let thumb = NSImage(cgImage: thumbCG, size: NSSize(width: thumbCG.width, height: thumbCG.height))
        var png = data
        if !isPNG, let full = CGImageSourceCreateImageAtIndex(src, 0, nil) {
            png = NSBitmapImageRep(cgImage: full).representation(using: .png, properties: [:]) ?? data
        }
        return .image(thumbnail: thumb, png: png, size: size)
    }

    func copy(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.content {
        case .text(let s): pb.setString(s, forType: .string)
        case .image(_, let png, _):
            pb.setData(png, forType: .png)
            if let img = NSImage(data: png), let tiff = img.tiffRepresentation { pb.setData(tiff, forType: .tiff) }
        }
        lastChange = pb.changeCount
        items.removeAll { $0.id == item.id }
        items.insert(ClipItem(content: item.content, date: Date(), sourceApp: item.sourceApp), at: 0)
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
    }

    func clear() {
        items.removeAll()
    }
}
